version: '3'

services:
  postgres:
    container_name: robotdreams6-postgres
    image: postgres:13.4
    env_file:
      - .env
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - robotdreams6-network
    ports:
      - "5432:5432"


volumes:
  database:


networks:
  robotdreams6-network:
    driver: bridge