"""Initial migration

Revision ID: 1c4b2d458853
Revises: 
Create Date: 2024-09-03 17:30:48.072961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c4b2d458853'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cve_records',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('assigner_org_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('assigner_short_name', sa.String(), nullable=False),
    sa.Column('date_reserved', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_published', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cve_records_id'), 'cve_records', ['id'], unique=False)
    op.create_table('references',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('tags', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_references_id'), 'references', ['id'], unique=False)
    op.create_table('affected_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cve_record_id', sa.String(), nullable=False),
    sa.Column('vendor', sa.String(), nullable=False),
    sa.Column('product', sa.String(), nullable=False),
    sa.Column('default_status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['cve_record_id'], ['cve_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_affected_products_id'), 'affected_products', ['id'], unique=False)
    op.create_table('cve_references',
    sa.Column('cve_record_id', sa.String(), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cve_record_id'], ['cve_records.id'], ),
    sa.ForeignKeyConstraint(['reference_id'], ['references.id'], )
    )
    op.create_table('problem_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cve_record_id', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['cve_record_id'], ['cve_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problem_types_id'), 'problem_types', ['id'], unique=False)
    op.create_table('product_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('affected_product_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('less_than', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('version_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['affected_product_id'], ['affected_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_versions_id'), 'product_versions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_versions_id'), table_name='product_versions')
    op.drop_table('product_versions')
    op.drop_index(op.f('ix_problem_types_id'), table_name='problem_types')
    op.drop_table('problem_types')
    op.drop_table('cve_references')
    op.drop_index(op.f('ix_affected_products_id'), table_name='affected_products')
    op.drop_table('affected_products')
    op.drop_index(op.f('ix_references_id'), table_name='references')
    op.drop_table('references')
    op.drop_index(op.f('ix_cve_records_id'), table_name='cve_records')
    op.drop_table('cve_records')
    # ### end Alembic commands ###
